/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir.sederhana;

import java.sql.*;
import javax.swing.*;;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class MenuUtama extends javax.swing.JFrame {
     private Connection koneksi;    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        
         tampilanutama.remove(jPanel2);
          tampilanutama.remove(jPanel3);
          tampilanutama.remove(jPanel4);
        tampilanutama.repaint();
        tampilanutama.revalidate();
        
        setVisible(true);
        setResizable(false);
        KoneksiDatabase();
        AutoNumber();
        TampilData();
        TampilData1();
        
        
         
    }
public void FilterHuruf(KeyEvent a) {
        if (Character.isDigit(a.getKeyChar())) {
            a.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Hanya Huruf", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
 
    //Method Untuk Menyaring Angka
    public void FilterAngka(KeyEvent b) {
        if (Character.isAlphabetic(b.getKeyChar())) {
            b.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
 
    //Method Untuk Menyaring Huruf Besar
    public void HurufBesar(KeyEvent c) {
        if (Character.isLowerCase(c.getKeyChar())) {
            c.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Hanya Huruf Besar", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
 
    //Method Untuk Menyaring Huruf Kecil
    public void HurufKecil(KeyEvent d) {
        if (Character.isUpperCase(d.getKeyChar())) {
            d.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Hanya Huruf Kecil", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
 
    //Method Untuk Membatasi Jumlah Karakter
    public void JumlahKarakter(KeyEvent e) {
        if (txtkodebarang.getText().length() == 10) {
            e.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Maksimal yang dimasukan Hanya 10 Karakter", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void JumlahKarakter1(KeyEvent e) {
        if (txtkodesupplier1.getText().length() == 10) {
            e.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Maksimal yang dimasukan Hanya 10 Karakter", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void JumlahKarakter2(KeyEvent e) {
        if (txttelp1.getText().length() == 12) {
            e.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Nomor Telepon dengan Benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jMenuItem11 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        tampilanutama = new javax.swing.JPanel();
        tpinputdata = new javax.swing.JPanel();
        txtkodebarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsatuan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txthargajual = new javax.swing.JTextField();
        txthargabeli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtkodesupplier1 = new javax.swing.JTextField();
        txtnamasupplier1 = new javax.swing.JTextField();
        txttelp1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtalamat1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldatasupplier1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatabarang = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setFocusable(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButton1.setText("INPUT BARANG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButton2.setText("DATA BARANG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButton8.setText("INPUT SUPPLIER");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButton9.setText("DATA SUPPLIER");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 300));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 530, 60));

        tampilanutama.setBackground(new java.awt.Color(255, 255, 255));
        tampilanutama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpinputdata.setBackground(new java.awt.Color(255, 255, 255));
        tpinputdata.setForeground(new java.awt.Color(255, 255, 255));

        txtkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodebarangActionPerformed(evt);
            }
        });
        txtkodebarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkodebarangKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkodebarangKeyTyped(evt);
            }
        });

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Satuan");

        txtsatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsatuanActionPerformed(evt);
            }
        });
        txtsatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsatuanKeyTyped(evt);
            }
        });

        jLabel6.setText("Buah");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/sederhana/img/icons8_add_file_16px_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/sederhana/img/icons8_edit_16px.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/sederhana/img/icons8_erase_16px.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/sederhana/img/icons8_trash_16px.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txthargajual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargajualKeyTyped(evt);
            }
        });

        txthargabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargabeliActionPerformed(evt);
            }
        });
        txthargabeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargabeliKeyTyped(evt);
            }
        });

        jLabel4.setText("Harga Beli");

        jLabel5.setText("Harga Jual");

        javax.swing.GroupLayout tpinputdataLayout = new javax.swing.GroupLayout(tpinputdata);
        tpinputdata.setLayout(tpinputdataLayout);
        tpinputdataLayout.setHorizontalGroup(
            tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpinputdataLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tpinputdataLayout.createSequentialGroup()
                        .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(tpinputdataLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(169, 169, 169)
                                .addComponent(jLabel5))
                            .addGroup(tpinputdataLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(173, 173, 173)
                                .addComponent(jLabel4))
                            .addGroup(tpinputdataLayout.createSequentialGroup()
                                .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txthargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tpinputdataLayout.createSequentialGroup()
                                .addComponent(txtkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txthargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 41, Short.MAX_VALUE))
                    .addGroup(tpinputdataLayout.createSequentialGroup()
                        .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tpinputdataLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addGroup(tpinputdataLayout.createSequentialGroup()
                                .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        tpinputdataLayout.setVerticalGroup(
            tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpinputdataLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tpinputdataLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tpinputdataLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tpinputdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tampilanutama.add(tpinputdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Nama Supplier");

        jLabel8.setText("Kode Supplier");

        txtkodesupplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodesupplier1ActionPerformed(evt);
            }
        });
        txtkodesupplier1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkodesupplier1KeyTyped(evt);
            }
        });

        txttelp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelp1KeyTyped(evt);
            }
        });

        jLabel9.setText("Telp.");

        jLabel10.setText("Alamat");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/sederhana/img/icons8_add_file_16px_1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/sederhana/img/icons8_edit_16px.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/sederhana/img/icons8_erase_16px.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/sederhana/img/icons8_trash_16px.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtnamasupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txttelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtkodesupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(txtalamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton7)
                            .addGap(6, 6, 6)
                            .addComponent(jButton10)
                            .addGap(6, 6, 6)
                            .addComponent(jButton11)
                            .addGap(6, 6, 6)
                            .addComponent(jButton12)))
                    .addContainerGap(68, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamasupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel8)
                    .addGap(6, 6, 6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtkodesupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtalamat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addComponent(jLabel7)
                    .addGap(100, 100, 100)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton7)
                        .addComponent(jButton10)
                        .addComponent(jButton11)
                        .addComponent(jButton12))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        tampilanutama.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 240));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tbldatasupplier1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Supplier", "Nama Supplier", "Alamat", "Telp."
            }
        ));
        tbldatasupplier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldatasupplier1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldatasupplier1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        tampilanutama.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 240));

        tbldatabarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Satuan", "Harga Beli", "Harga Jual"
            }
        ));
        tbldatabarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldatabarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldatabarang);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        tampilanutama.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 240));

        getContentPane().add(tampilanutama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 530, 240));

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/sederhana/img/icons8_bulleted_list_30px.png"))); // NOI18N
        jMenu7.setMaximumSize(new java.awt.Dimension(46, 36));
        jMenuBar1.add(jMenu7);

        jMenu1.setText("Transaksi");

        jMenuItem2.setText("Penjual");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Pembeli");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Stock");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laporan");

        jMenu5.setText("Penjual");

        jMenuItem1.setText("jMenuItem1");
        jMenu5.add(jMenuItem1);

        jMenuItem5.setText("jMenuItem5");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("jMenuItem6");
        jMenu5.add(jMenuItem6);

        jMenu2.add(jMenu5);

        jMenu6.setText("Pembeli");

        jMenuItem7.setText("jMenuItem7");
        jMenu6.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jMenu6.add(jMenuItem8);

        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Master");

        jMenuItem9.setText("Barang");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Suplier");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tools");
        jMenuBar1.add(jMenu4);

        jMenu8.setText("Log Out");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    tampilanutama.removeAll();
    tampilanutama.repaint();
    tampilanutama.revalidate();
    
    tampilanutama.add(tpinputdata);
    tampilanutama.repaint();
    tampilanutama.revalidate();
    
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     tampilanutama.removeAll();
    tampilanutama.repaint();
    tampilanutama.revalidate();
    
    tampilanutama.add(jPanel4);
    tampilanutama.repaint();
    tampilanutama.revalidate();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String nim = txtkodebarang.getText();
String nama = txtnamabarang.getText();
String jurusan = txtsatuan.getText();
String semester = txthargabeli.getText();
String hargajual = txthargajual.getText();


if (txtkodebarang.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(null, "Mohon Masukkan Data untuk di Input", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
} else {
     try {
         java.sql.Statement stat = koneksi.createStatement();
         ResultSet data = stat.executeQuery("SELECT * FROM tabelkasir WHERE kodebarang ='" + txtkodebarang.getText() + "'");
         if (data.next()) {
             JOptionPane.showMessageDialog(null, "Kode Barang Sudah Ada", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
             txtkodebarang.requestFocus();
         } else {
            String sql = "INSERT INTO tabelkasir VALUES('" + nim + "'"
                   + ",'" + semester + "'"
                   + ",'" + jurusan + "'"
                   + ",'" + semester + "'"
                   + ",'" + hargajual+ "')";
            stat.executeUpdate(sql);
            txtkodebarang.setText("");
            txtnamabarang.setText("");
            txtsatuan.setText("");
             txthargabeli.setText("");
              txthargajual.setText("");
            txtkodebarang.requestFocus();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);           
            TampilData();
         }
            stat.close();
        } catch (Exception exc) {
            System.err.println("Terjadi Kesalahan :" + exc);
     }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    tampilanutama.removeAll();
    tampilanutama.repaint();
    tampilanutama.revalidate();
    
    tampilanutama.add(jPanel2);
    tampilanutama.repaint();
    tampilanutama.revalidate();            // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    tampilanutama.removeAll();
    tampilanutama.repaint();
    tampilanutama.revalidate();
    
    tampilanutama.add(jPanel3);
    tampilanutama.repaint();
    tampilanutama.revalidate();              // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    String nim = txtkodesupplier1.getText();
String nama = txtnamasupplier1.getText();
String jurusan = txtalamat1.getText();
String semester = txttelp1.getText();



if (txtkodesupplier1.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(null, "Mohon Masukkan Data untuk di Input", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
} else {
     try {
         java.sql.Statement stat = koneksi.createStatement();
         ResultSet data = stat.executeQuery("SELECT * FROM tabelsuplier WHERE kodesuplier ='" + txtkodesupplier1.getText() + "'");
         if (data.next()) {
             JOptionPane.showMessageDialog(null, "Kode Suplier Sudah Ada", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
             txtkodesupplier1.requestFocus();
         } else {
            String sql = "INSERT INTO tabelsuplier VALUES('" + nim + "'"
                   + ",'" + nama + "'"
                   + ",'" + jurusan + "'"
                   + ",'" + semester + "')";
            stat.executeUpdate(sql);
            txtkodesupplier1.setText("");
            txtnamasupplier1.setText("");
            txtalamat1.setText("");
            txttelp1.setText("");
            txtkodesupplier1.requestFocus();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);           
            TampilData1();
         }
            stat.close();
        } catch (Exception exc) {
            System.err.println("Terjadi Kesalahan :" + exc);
     }
     
}       // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtkodesupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodesupplier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodesupplier1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin mengubah data ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
if (ok == 0) {
String sql = "update tabelkasir set namabarang='" + txtnamabarang.getText()
        + "',satuan='" + txtsatuan.getText()
        + "',hargabeli='" + txthargabeli.getText()
        + "',hargajual='" + txthargajual.getText()
        + "'where kodebarang='" + txtkodebarang.getText().trim() + "'";
if (txtkodebarang.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(null, "Data Masih Kosong!", "Ubah Data", JOptionPane.WARNING_MESSAGE);
    txtkodebarang.requestFocus();
} else {
    try {
         Statement stat = koneksi.createStatement();
         stat.executeUpdate(sql);
         JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah", "Ubah Data", JOptionPane.INFORMATION_MESSAGE);
         stat.close();
         txtkodebarang.setText("");
                txtnamabarang.setText("");
                txtsatuan.setText("");
                txthargabeli.setText("");
                txthargajual.setText("");
         txtkodebarang.requestFocus();
         TampilData();
    } catch (Exception exc) {
        System.err.println("Error :" + exc);
    }
  }
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     txtkodebarang.setText("");
                txtnamabarang.setText("");
                txtsatuan.setText("");
                txthargabeli.setText("");
                txthargajual.setText("");
                txtkodebarang.requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "DELETE FROM tabelkasir WHERE kodebarang='" + txtkodebarang.getText().trim() + "'";
            try {
                Statement stat = koneksi.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus", "Hapus Data", JOptionPane.INFORMATION_MESSAGE);
                stat.close();
                txtkodebarang.setText("");
                txtnamabarang.setText("");
                txtsatuan.setText("");
                txthargabeli.setText("");
                txthargajual.setText("");
                txtkodebarang.requestFocus();
                TampilData();
               
            } catch (SQLException exc) {
                System.err.println(sql);
                System.err.println("Error : " + exc);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tbldatabarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldatabarangMouseClicked
    int baris = tbldatabarang.getSelectedRow();
        if (baris != -1) {
            txtkodebarang.setText(tbldatabarang.getValueAt(baris, 0).toString());
            txtnamabarang.setText(tbldatabarang.getValueAt(baris, 1).toString());
            txtsatuan.setText(tbldatabarang.getValueAt(baris, 2).toString());
            txthargabeli.setText(tbldatabarang.getValueAt(baris, 3).toString());
            txthargajual.setText(tbldatabarang.getValueAt(baris, 4).toString());
            tampilanutama.removeAll();
    tampilanutama.repaint();
    tampilanutama.revalidate();
    tampilanutama.add(tpinputdata);
    tampilanutama.repaint();
    tampilanutama.revalidate();
          }
       
        
        
              // TODO add your handling code here:
    }//GEN-LAST:event_tbldatabarangMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin mengubah data ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
if (ok == 0) {
String sql = "update tabelsuplier set namasuplier='" + txtnamasupplier1.getText()
        + "',alamat='" + txtalamat1.getText()
        + "',telp='" + txttelp1.getText()
        
        + "'where kodesuplier='" + txtkodesupplier1.getText().trim() + "'";
if (txtkodesupplier1.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(null, "Data Masih Kosong!", "Ubah Data", JOptionPane.WARNING_MESSAGE);
    txtkodesupplier1.requestFocus();
} else {
    try {
         Statement stat = koneksi.createStatement();
         stat.executeUpdate(sql);
         JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah", "Ubah Data", JOptionPane.INFORMATION_MESSAGE);
         stat.close();
         txtkodesupplier1.setText("");
         txtnamasupplier1.setText("");
         txtalamat1.setText("");
         txttelp1.setText("");              
         txtkodesupplier1.requestFocus();
         TampilData1();
    } catch (Exception exc) {
        System.err.println("Error :" + exc);
    }}}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    txtnamasupplier1.setText("");
    txtkodesupplier1.setText("");   
txtalamat1.setText("");   
txttelp1.setText("");   
txtkodesupplier1.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed
    
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "DELETE FROM tabelsuplier WHERE kodesuplier='" + txtkodesupplier1.getText().trim() + "'";
            try {
                Statement stat = koneksi.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus", "Hapus Data", JOptionPane.INFORMATION_MESSAGE);
                stat.close();
                txtkodesupplier1.setText("");
                txtnamasupplier1.setText("");
                txtalamat1.setText("");
                txttelp1.setText("");
               
                txtkodesupplier1.requestFocus();
                TampilData1();
               
            } catch (SQLException exc) {
                System.err.println(sql);
                System.err.println("Error : " + exc);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void tbldatasupplier1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldatasupplier1MouseClicked
     int baris = tbldatasupplier1.getSelectedRow();
        if (baris != -1) {
            txtkodesupplier1.setText(tbldatasupplier1.getValueAt(baris, 0).toString());
            txtnamasupplier1.setText(tbldatasupplier1.getValueAt(baris, 1).toString());
            txtalamat1.setText(tbldatasupplier1.getValueAt(baris, 2).toString());
            txttelp1.setText(tbldatasupplier1.getValueAt(baris, 3).toString());
            
            tampilanutama.removeAll();
    tampilanutama.repaint();
    tampilanutama.revalidate();
    tampilanutama.add(jPanel2);
    tampilanutama.repaint();
    tampilanutama.revalidate();
          }        // TODO add your handling code here:
    }//GEN-LAST:event_tbldatasupplier1MouseClicked

    private void txtkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodebarangActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_txtkodebarangActionPerformed

    private void txtkodebarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodebarangKeyPressed
    JumlahKarakter(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodebarangKeyPressed

    private void txtkodebarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodebarangKeyTyped
    JumlahKarakter(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodebarangKeyTyped

    private void txtkodesupplier1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodesupplier1KeyTyped
    JumlahKarakter1(evt);    // TODO add your handling code here:
    }//GEN-LAST:event_txtkodesupplier1KeyTyped

    private void txtsatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsatuanActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtsatuanActionPerformed

    private void txtsatuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsatuanKeyTyped
    FilterAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtsatuanKeyTyped

    private void txthargajualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargajualKeyTyped
    FilterAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txthargajualKeyTyped

    private void txthargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargabeliActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txthargabeliActionPerformed

    private void txthargabeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargabeliKeyTyped
    FilterAngka(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_txthargabeliKeyTyped

    private void txttelp1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelp1KeyTyped
    FilterAngka(evt);
    JumlahKarakter2(evt);// TODO add your handling code here:
    }//GEN-LAST:event_txttelp1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel tampilanutama;
    private javax.swing.JTable tbldatabarang;
    private javax.swing.JTable tbldatasupplier1;
    private javax.swing.JPanel tpinputdata;
    private javax.swing.JTextField txtalamat1;
    private javax.swing.JTextField txthargabeli;
    private javax.swing.JTextField txthargajual;
    private javax.swing.JTextField txtkodebarang;
    private javax.swing.JTextField txtkodesupplier1;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtnamasupplier1;
    private javax.swing.JTextField txtsatuan;
    private javax.swing.JTextField txttelp1;
    // End of variables declaration//GEN-END:variables

    private void KoneksiDatabase() {
     try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException cnf) {
        }
        try {
            koneksi = DriverManager.getConnection("jdbc:mysql://localhost/loginkasir", "root", "");
            JOptionPane.showMessageDialog(null, "Koneksi Database Berhasil");
        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Tidak Berhasil");
        } catch (Exception e) {
        }    
    }

    private void AutoNumber() {
     
    }

    private void TampilData() {
      DefaultTableModel model = new DefaultTableModel();
        tbldatabarang.setModel(model);
        model.addColumn("kodebarang");
        model.addColumn("namabarang");
        model.addColumn("satuan");
        model.addColumn("hargabeli");
        model.addColumn("hargajual");

        try {
            java.sql.Statement stat = koneksi.createStatement();
    ResultSet data = stat.executeQuery("SELECT * FROM tabelkasir");
    while (data.next()) {
         model.addRow(new Object[]{
            data.getString("kodebarang"),
            data.getString("namabarang"),
            data.getString("satuan"),
            data.getString("hargabeli"),
            data.getString("hargajual")
         });
         tbldatabarang.setModel(model);
    }
} catch (Exception e) {
    System.err.println("Terjadi Kesalahan :" + e);
}
    }    
private void TampilData1() {
    DefaultTableModel model = new DefaultTableModel();
        tbldatasupplier1.setModel(model);
        model.addColumn("kodesuplier");
        model.addColumn("namasuplier");
        model.addColumn("alamat");
        model.addColumn("telp");
        try {
            java.sql.Statement stat = koneksi.createStatement();
    ResultSet data = stat.executeQuery("SELECT * FROM tabelsuplier");
    while (data.next()) {
         model.addRow(new Object[]{
            data.getString("kodesuplier"),
            data.getString("namasuplier"),
            data.getString("alamat"),
            data.getString("telp"),
         });
         tbldatasupplier1.setModel(model);
    }
} catch (Exception e) {
    System.err.println("Terjadi Kesalahan :" + e);
}
        
        }
    
}
